### ISSUE TITLE
Website does not appear to render correctly on FF32

### ISSUE THREAD

**Issue by lvh** [nginx-clojure/nginx-clojure.github.io#1]
Works fine for me in Chrome.

![nginx-clojure](https://cloud.githubusercontent.com/assets/97816/4595203/08f18634-5097-11e4-97b7-2976b7904c1c.png)

**Comment by xfeep** [comment]
This site use CDN http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.11.0.min.js
for jquery , so for security the browser won't load these javascript source
when we access it by HTTPS.

Regards.
Xfeep

**Comment by xfeep** [comment]
We fixed it just now. Please try again.
